### ISSUE TITLE
Some metrics are calculated differently from paper

### ISSUE THREAD

**Issue by Kihy** [ymirsky/Kitsune-py#10]
Hi 

I have noticed that some metrics are calculated differently from what is described in the paper, in particular:

- Radius. Radius in the paper is defined as sqrt(var1^2+var2^2), however in AfterImage.py, line 88, it is calculated as sqrt(var1+var2)

- Covariance. The paper defines covariance as SR_ij/(w_i+w_j), but in AfterImage.py, line 203, it defines a new weight w3 and divides SR_ij by w3.

Could you please clarify why these two metrics are calculated differently?

**Comment by ymirsky** [comment]
Hello,

- Yes, this seems to be a bug, but it should not affect the performance. It is now fixed -thanks!
- This is an upgraded version that tries to decay the residual
