### ISSUE TITLE
Compilation fails on Windows with C:\\\\MinGW\\\\bin\\\\gcc.exe' failed with exit status 1\n

### ISSUE THREAD

**Issue by abbdulwahab86** [ymirsky/Kitsune-py#2]
Compilation fails on Windows with C:\\\\MinGW\\\\bin\\\\gcc.exe' failed with exit status 1\n

**Comment by ymirsky** [comment]
I have added a pure Python version of AfterImage. Change the netStat.py file to import AfterImage_NDSS.py instead. It will be slower since it is not Cython.
