### ISSUE TITLE
How do I fit my own features without using pcap files?

### ISSUE THREAD

**Issue by SandeepaDevin** [ymirsky/Kitsune-py#21]
I'm using network packets from my elasticsearch and I wanna know how do I fit my own features to this. 
Is it possible to use different data than a pcap file or is it necessary to use pcap ?

**Comment by ymirsky** [comment]
If you don't need the feature extractor (just the anomaly detector) then
check out my other repository (KitNET)
*Dr. Yisroel Mirsky*
*Head of the Offensive AI Research Lab*
*Department of Software and Information Systems Engineering*
*Ben-Gurion University*

**Comment by SandeepaDevin** [comment]
I'd check it out. Thanks!
