### ISSUE TITLE
Not able to run example 

### ISSUE THREAD

**Issue by mkcl4** [ymirsky/Kitsune-py#4]
![Screenshot 2019-04-04 at 4 02 55 PM](https://user-images.githubusercontent.com/48287979/55539410-26d44d00-56f3-11e9-8074-aeb24a9fd896.png)

Hi, I have the following in the virtualenv 
Package    Version
---------- -------
Cython     0.29.6 
numpy      1.16.2 
pip        19.0.3 
scapy      2.4.2  
setuptools 40.9.0 
wheel      0.33.1

When it run it give error such as "

Importing AfterImage Cython Library
Importing Scapy Library
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from Kitsune import Kitsune
  File "/home/pi/vir1/Kitsune-py/Kitsune.py", line 2, in <module>
    from KitNET.KitNET import KitNET
  File "/home/pi/vir1/Kitsune-py/KitNET/KitNET.py", line 2, in <module>
    import KitNET.dA as AE
ImportError: No module named dA
"

Please advise thanks

**Comment by ymirsky** [comment]
It seems that your environment cannot see the KitNET folder from within the KitNET module. The simple (ugly) fix to this is to flatten the KitNET module:

1. Move the contents of the KitNET folder to the main directory.
2. Do a search replace for "KitNET." -> "" in all source code files

**Comment by mkcl4** [comment]
Hi Ymirshy, Thanks for the response, as per your advise I have cp the Kismet to the main was able to run the example.py until the below appear

![Screenshot 2019-04-05 at 3 38 59 PM](https://user-images.githubusercontent.com/48287979/55611850-59487d80-57b9-11e9-8905-7107b6144fa6.png)

Can u advise on this

**Comment by Amos-Zhu** [comment]
![image](https://user-images.githubusercontent.com/47839247/57218037-e71cc000-7026-11e9-9e32-dbb1fefe4796.png)
hi,how can i solve this problem

**Comment by ymirsky** [comment]
I've noticed that some people are having this error if they are not running
anaconda or they're using a Mac for some reason...

The simple fixe is to copy the contents of the directory 'afterimage' into
the running directory (typically the parent directory).

I will try to find time to fix this with a commit later on...

**Comment by Amos-Zhu** [comment]
thanks for answer
Thanks for the answer. I can now run example.Py, but the whole process is not clear, such as what is the implementation of the Autoencoding part


| |
amos_zjj
|
|
amos_zjj@163.com
|
签名由网易邮箱大师定制
On 5/6/2019 17:59，Yisroel Mirsky<notifications@github.com> wrote：
I've noticed that some people are having this error if they are not running
anaconda or they're using a Mac for some reason...

The simple fixe is to copy the contents of the directory 'afterimage' into
the running directory (typically the parent directory).

I will try to find time to fix this with a commit later on...

**Comment by enchaowu** [comment]
solution:
before the line
import AfterImage as af
add 
import pyximport
pyximport.install()

> ![image](https://user-images.githubusercontent.com/47839247/57218037-e71cc000-7026-11e9-9e32-dbb1fefe4796.png)
> hi,how can i solve this problem

**Comment by ymirsky** [comment]
I have added your fix. Seems that some machines are sensitive to this. thanks!
