### ISSUE TITLE
In the AfterImage.pyx, the method get_last() of Class Queue.  

### ISSUE THREAD

**Issue by yanghaku** [ymirsky/Kitsune-py#8]
in the AfterImage.pyx , Class Queue:

```python3

    cdef insert(self,double v):
        self.q[self.indx] = v
        self.indx = (self.indx + 1) % 3
        self.n += 1

    cdef get_last(self):
        return self.q[self.indx]

```
when n is 1 or 2,  calling the 'get_last' will always get 0.
when n is 3, calling the 'get_last' will get the  first element in queue not the last.
I'd like to ask if it should be written like this : ```return self.q[(self.indx-1)%3]```

**Comment by ymirsky** [comment]
You're right! Thanks for catching this.
By the way, this pyx version performs extrapolation. A faster version is the NDSS version without extrapolation. The python file is now in the repo as Afterimage_NDSS.py
